_BASE_: "Base_RCNN_FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 13
DATASETS:
  TRAIN: ("deepfashion_train",)
  TEST: ("deepfashion_validation",)
SOLVER:
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 10000
  STEPS: (210000, 250000)
  MAX_ITER: 300000
TEST:
  EVAL_PERIOD: 10000
